version: "2.1"
services:
  redis:
    hostname: redis
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 30
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data/
    expose:
      - 5432
  worker:
    build:
      context: .
      dockerfile: dockerfile
    command: celery -A test_celery worker --concurrency=4 --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  celery-beat:
    build:
      context: .
      dockerfile: dockerfile
    command: celery -A test_celery beat --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      